apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql-accounts.fullname" . }}
  labels:
    {{- include "postgresql-accounts.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ .Values.auth.postgresPassword | b64enc | quote }}
  password: {{ .Values.auth.password | b64enc | quote }}
  database: {{ .Values.auth.database | b64enc | quote }}
  username: {{ .Values.auth.username | b64enc | quote }}