spring:
  application:
    name: frontui
  config:
    import: "optional:consul:"
  cloud:
    consul:
      host: ${SPRING_CLOUD_CONSUL_HOST:localhost}
      port: ${SPRING_CLOUD_CONSUL_PORT:8500}
      discovery:
        enabled: true
        service-name: ${spring.application.name}
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: frontui-client
            client-secret: ${FRONTUI_CLIENT_SECRET}
            authorization-grant-type: client_credentials
            scope: openid
        provider:
          keycloak:
            token-uri: http://bankapp-keycloak:8080/realms/bankapp/protocol/openid-connect/token

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

accounts:
  service:
    url: http://gateway/accounts

rsa:
  public-key: classpath:certs/public.pem

server:
  port: 8081