apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cash.fullname" . }}-keycloak
  labels:
    {{- include "cash.labels" . | nindent 4 }}
type: Opaque
data:
  client-secret: {{ .Values.keycloak.client.secretValue | b64enc | quote }}