apiVersion: v1
kind: Service
metadata:
  name: {{ include "elasticsearch.fullname" . }}
  labels:
    {{- include "elasticsearch.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9200
      name: http
    - port: {{ .Values.service.transportPort }}
      targetPort: 9300
      name: transport
  selector:
    {{- include "elasticsearch.selectorLabels" . | nindent 4 }}