spring:
  application:
    name: transfer
  config:
    import: "optional:consul:"
  cloud:
    consul:
      host: ${SPRING_CLOUD_CONSUL_HOST:localhost}
      port: ${SPRING_CLOUD_CONSUL_PORT:8500}
      discovery:
        enabled: true
        service-name: ${spring.application.name}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://bankapp-keycloak:8080/realms/bankapp
      client:
        registration:
          keycloak:
            client-id: transfer-client
            client-secret: TRANSFER-client-secret-123456
            authorization-grant-type: client_credentials
            scope: accounts-access,notifications-access
        provider:
          keycloak:
            token-uri: http://bankapp-keycloak:8080/realms/bankapp/protocol/openid-connect/token

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

rsa:
  public-key: classpath:certs/public.pem

gateway:
  url: http://gateway

server:
  port: 8086

logging:
  level:
    root: INFO
    ru.yandex.practicum.transfer: INFO
    org.springframework.security: DEBUG