apiVersion: v2
name: bankapp
description: Umbrella chart for bankapp application
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: postgresql-accounts
    version: 0.1.0
    repository: "file://./charts/postgresql-accounts"
  - name: postgresql-exchange
    version: 0.1.0
    repository: "file://./charts/postgresql-exchange"
  - name: accounts
    version: 0.1.0
    repository: "file://./charts/accounts"
  - name: blocker
    version: 0.1.0
    repository: "file://./charts/blocker"
  - name: cash
    version: 0.1.0
    repository: "file://./charts/cash"
  - name: exchange
    version: 0.1.0
    repository: "file://./charts/exchange"
  - name: frontui
    version: 0.1.0
    repository: "file://./charts/frontui"
  - name: generator
    version: 0.1.0
    repository: "file://./charts/generator"
  - name: notifications
    version: 0.1.0
    repository: "file://./charts/notifications"
  - name: transfer
    version: 0.1.0
    repository: "file://./charts/transfer"
  - name: postgresql-keycloak
    version: 0.1.0
    repository: "file://./charts/postgresql-keycloak"
  - name: keycloak
    version: 0.1.0
    repository: "file://./charts/keycloak"
  - name: kafka
    version: 0.1.0
    repository: "file://./charts/kafka"