apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bankapp-frontui-metrics
  namespace: test
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      monitoring: enabled
      monitoring-path: custom
  endpoints:
    - port: http
      path: /frontui/actuator/prometheus
      interval: 30s