spring:
  application:
    name: accounts
  datasource:
    url: jdbc:postgresql://${SPRING_DATASOURCE_HOST}:${SPRING_DATASOURCE_PORT}/${SPRING_DATASOURCE_NAME}
    username: ${SPRING_DATASOURCE_USER}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    baseline-version: 0
    validate-on-migrate: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://bankapp-keycloak:8080/realms/bankapp
      client:
        registration:
          keycloak:
            client-id: accounts-client
            client-secret: ${ACCOUNTS_CLIENT_SECRET}
            authorization-grant-type: client_credentials
            scope: openid
        provider:
          keycloak:
            token-uri: http://bankapp-keycloak:8080/realms/bankapp/protocol/openid-connect/token
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

server:
  port: 8080

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

jwt:
  expiration: 3600000

logging:
  level:
    root: INFO
    ru.yandex.practicum.accounts: INFO
    ru.yandex.practicum.accounts.configuration: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.security.oauth2.server.resource: TRACE
    org.springframework.security.oauth2.jwt: TRACE
    org.springframework.web.client: DEBUG
