apiVersion: v1
kind: Secret
metadata:
  name: {{ include "transfer.fullname" . }}-keycloak
  labels:
    {{- include "transfer.labels" . | nindent 4 }}
type: Opaque
data:
  client-secret: {{ .Values.keycloak.client.secretValue | b64enc | quote }}