apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "generator.fullname" . }}
  labels:
    {{- include "generator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "generator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "generator.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: generator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: GENERATOR_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "generator.fullname" . }}-keycloak
                  key: client-secret
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: {{ .Values.kafka.server | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}